[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

# Authorize users to upload files with messages
multi_modal = false


[UI]
# Name of the app and chatbot.
name = "JC-WebChat"

# Show the readme while the conversation is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
# description = ""

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = true

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
github = "https://github.com/JC0v0/JC-WebChat"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
    background = "#FFFFFF"
    paper = "#FFFFFF"

    [UI.theme.light.primary]
        main = "#888888"
        #dark = "#FFFFFF"
        light = "#FFFFFF"

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]
    #background = "#000000"
    #paper = "#FFFFFF"

    [UI.theme.dark.primary]
        main = "#888888"
        #dark = "#FFFFFF"
        #light = "#000000"


[meta]
generated_by = "0.7.301"

